### PR TITLE
Update validator app

### PR DESCRIPTION
**Pull request by radamson**
Updates the docker-compose and nginx configuration to support the community validator app and updated validation service.

steps to update

```shell
# update images to get the latest
docker-compose pull

# rebuild and execute
docker-compose up --build
```

Also adds the validator to the landing page

image

**Submitter:**
- [ ] This pull request describes why these changes were made
- [ ] Internal ticket for this PR:
- [ ] Internal ticket links to this PR
- [ ] Internal ticket is properly labeled (Community/Program)
- [ ] Internal ticket has a justification for its Community/Program label
- [ ] Code diff has been reviewed for extraneous/missing code

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure
      where appropriate, and accomplishes the task's purpose
- [ ] You have tried to break the code

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure
      where appropriate, and accomplishes the task's purpose
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by arscan** [comment]
Updated to just be a new button under Community Edition, because this is a 'Community' feature, and having a whole extra box is a bit more visual weight than I think we want right now.  A light touch is better I think.

Screen Shot 2020-08-05 at 4 43 10 PM

**Review by arscan — APPROVED** [review]
Could you take a quick look at my update to make sure it looks good before merging?

**Comment by radamson** [comment]
I like it.  I wonder if we should do something about the `Download` Link since it only applies to the Community Tests.

Tested it out again and everything still worked.

**Comment by arscan** [comment]
> I wonder if we should do something about the Download Link since it only applies to the Community Tests.

Yeah, I noticed that too.  I'm not quite sure what the use case is to run that locally though (vs. inferno, which you need to do in order to run your own tests).  Now that this is up there I'm sure we'll iterate.

**Pull request merged**
